### ISSUE TITLE
Open VPN script - trouble with client certs

### ISSUE THREAD

**Issue by bbusche** [digitalocean/do_user_scripts#28]
I used the Open VPN userdata script when building my droplet. Presumably I now need to continue at step 3 of the tutorial at https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-14-04

But when I try to execute the command './build-key client1', it gives me the following error:

  Please edit the vars script to reflect your configuration,
  then source it with "source ./vars".
  Next, to start with a fresh PKI configuration and to delete any
  previous certificates and keys, run "./clean-all".
  Finally, you can run this tool (pkitool) to build certificates/keys.

**Comment by andrewsomething** [comment]
Hi!

The script actually takes care of that part too. See: 

https://github.com/digitalocean/do_user_scripts/blob/master/Ubuntu-14.04/network/open-vpn.yml#L44

A bundled client profile (`client.ovpn`) as well as a CA certificate (`ca.crt`), user certificate (`client1.key`), and user private key (`client1.crt`) are all generated and can be found in the `/root` directory. You should be able to jump right to step 5 of that tutorial.

**Comment by bbusche** [comment]
I tried that. I am getting TLS errors, and I see some of the comments below the article reflect this as well. Is a TLS issue a case of the client cert not matching the server cert?

**Comment by ao95** [comment]
On line [56](https://github.com/digitalocean/do_user_scripts/blob/master/Ubuntu-14.04/network/open-vpn.yml#L56) there is an error, it will add the certificate in both text and base64. 
It's only the part between `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` (i.e base64 certificate) which should be added to the client.ovpn file. 
I guess that's why people gets TLS errors.

My suggestion is to replace `cat /etc/openvpn/easy-rsa/keys/client1.crt` with `openssl x509 -in /etc/openvpn/easy-rsa/keys/client1.crt -outform PEM`

**Comment by andrewsomething** [comment]
Thanks @ao95 I've merged your change. If anyone else is still seeing issues, please feel free to open a new issue.
